const express=require("express"),multer=require("multer"),Database=require("better-sqlite3"),path=require("path"),fs=require("fs"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||10000,PASS=process.env.ADMIN_PASSWORD||"64713",DATA=process.env.DATA_DIR||path.join(__dirname,"data");
const IMG=path.join(DATA,"images"),FIL=path.join(DATA,"files");fs.mkdirSync(IMG,{recursive:true});fs.mkdirSync(FIL,{recursive:true});
const db=new Database(path.join(DATA,"edit-zone-bd.db"));db.exec("CREATE TABLE IF NOT EXISTS templates(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',image_name TEXT NOT NULL,file_name TEXT NOT NULL,original_file_name TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
const sessions=new Set();
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static("public"));
function auth(req,res,next){let t=req.headers.authorization?.replace(/^Bearer /,"");if(!t||!sessions.has(t))return res.status(401).json({error:"Unauthorized"});next()}
const storage=multer.diskStorage({destination:(r,f,cb)=>cb(null,f.fieldname==="image"?IMG:FIL),filename:(r,f,cb)=>cb(null,crypto.randomBytes(18).toString("hex")+path.extname(f.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:50*1024*1024},fileFilter:(r,f,cb)=>{if(f.fieldname==="image"&&!/^image\/(jpeg|png|webp|gif)$/.test(f.mimetype))return cb(new Error("Only JPG, PNG, WEBP or GIF images are allowed."));if(/\.(php|phtml|php3|php4|php5|phar|cgi|pl|asp|aspx|jsp|js|sh)$/i.test(f.originalname))return cb(new Error("This file type is not allowed."));cb(null,true)}}).fields([{name:"image",maxCount:1},{name:"file",maxCount:1}]);
app.post("/api/login",(r,s)=>{if(r.body.password!==PASS)return s.status(401).json({error:"Incorrect password"});let t=crypto.randomBytes(32).toString("hex");sessions.add(t);s.json({token:t})});
app.post("/api/logout",auth,(r,s)=>{sessions.delete(r.headers.authorization.replace(/^Bearer /,""));s.json({ok:true})});
app.get("/api/templates",(r,s)=>s.json(db.prepare("SELECT * FROM templates ORDER BY id DESC").all().map(t=>({...t,image_url:"/uploads/images/"+t.image_name,file_url:"/uploads/files/"+t.file_name}))));
app.use("/uploads/images",express.static(IMG));app.use("/uploads/files",express.static(FIL));
app.post("/api/templates",auth,(r,s)=>upload(r,s,e=>{if(e)return s.status(400).json({error:e.message});let title=(r.body.title||"").trim(),desc=(r.body.description||"").trim(),im=r.files?.image?.[0],f=r.files?.file?.[0];if(!title||!im||!f)return s.status(400).json({error:"Name, preview image and template file are required."});let x=db.prepare("INSERT INTO templates(title,description,image_name,file_name,original_file_name) VALUES(?,?,?,?,?)").run(title,desc,im.filename,f.filename,f.originalname);s.json({ok:true,id:x.lastInsertRowid})}));
app.delete("/api/templates/:id",auth,(r,s)=>{let t=db.prepare("SELECT * FROM templates WHERE id=?").get(r.params.id);if(!t)return s.status(404).json({error:"Not found"});try{fs.unlinkSync(path.join(IMG,t.image_name))}catch{}try{fs.unlinkSync(path.join(FIL,t.file_name))}catch{}db.prepare("DELETE FROM templates WHERE id=?").run(r.params.id);s.json({ok:true})});
app.get("/health",(r,s)=>s.json({ok:true}));app.get("*",(r,s)=>s.sendFile(path.resolve("public/index.html")));app.listen(PORT,()=>console.log("EDIT ZONE BD on "+PORT));
